services:
  test_ci:
    build:
      context: .
      target: builder
      dockerfile: docker/backend.Dockerfile
    command: python -m unittest discover -s tests -v
    volumes:
      - .:/src
    depends_on:
      mongo:
        condition: service_started
    environment:
      # these are the test environment variables.
      - MONGO_DB_NAME=testregistry
      - MONGO_URI=mongodb://mongo:27017/testregistry
      - MONGO_USER_NAME=testuser
      - MONGO_PASSWORD=testpassword
      - SALT=MYSALT
      - HOST=localhost
      - RESET_EMAIL=reset@localhost.com
      - RESET_PASSWORD=resetpass
      - SUDO_PASSWORD=fortranpass
      - IS_CI=true
      - JWT_SECRET_KEY=test-jwt-secret-key

  mongo:
    image: mongo:latest
    healthcheck:
      test: ["CMD", "mongosh", "--eval", "db.adminCommand('ping')"]
      interval: 5s
      timeout: 5s
      retries: 5
